name: bdl_ood
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.8
  - pip
  - git
  ## Scientific Computing
  - numpy>=1.18
  - scipy>=1.3
  ## Visualization
  - jupyter>=1.0
  - matplotlib>=3.1
  - seaborn>=0.11
  ## Data I/O
  - pandas>=0.22
  - dill>=0.2
  ## Machine Learning
  - scikit-learn>=1.1.0
    ## PyTorch Autodiff
  - pytorch::pytorch>=1.11
  - pytorch::cpuonly
  - pytorch::torchvision
  ## JAX autodiff
  - pip:
    - jax[cpu]>=0.3.17
    - numpyro[cpu]>=0.10.0
  
